format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$fennel\
$typst\
$vagrant\
$conda\
$meson\
$memory_usage\
$aws\
$gcloud\
$openstack\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

# Sets user-defined palette
palette            = "zenwritten"

add_newline        = false

[line_break]
disabled           = true

[battery]
full_symbol        = 'ğŸ”‹ '
charging_symbol    = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[character]
success_symbol     = "[â¯](lavender)"
error_symbol       = "[â¯](red)"
vimcmd_symbol      = "[â®](green)"

[directory]
truncation_length  = 4
# Catppuccin 'lavender'
style              = "bold lavender"
read_only          = " ó°Œ¾"


# Symbols -----------------------------------------------------------------------
[aws]
symbol             = "îŒ½  "

[buf]
symbol             = "ï’ "

[c]
symbol             = "î˜ "

[conda]
symbol             = "ï„Œ "

[crystal]
symbol             = "î˜¯ "

[dart]
symbol             = "î˜ "

[docker_context]
symbol             = "ïŒˆ "

[elixir]
symbol             = "î˜­ "

[elm]
symbol             = "î˜¬ "

[fennel]
symbol             = "îš¯ "

[fossil_branch]
symbol             = "ï˜ "

[git_branch]
symbol             = "ï˜ "

[golang]
symbol             = "î˜§ "

[guix_shell]
symbol             = "ïŒ¥ "

[haskell]
symbol             = "î· "

[haxe]
symbol             = "î™¦ "

[hg_branch]
symbol            = "ï˜ "

[hostname]
ssh_symbol        = "î¬ "

[java]
symbol            = "î‰– "

[julia]
symbol            = "î˜¤ "

[kotlin]
symbol            = "î˜´ "

[lua]
symbol            = "î˜  "

[memory_usage]
symbol            = "ó°› "

[meson]
symbol            = "ó°”· "

[nim]
symbol            = "ó°†¥ "

[nix_shell]
symbol            = "ïŒ“ "

[nodejs]
symbol            = "îœ˜ "

[ocaml]
symbol            = "î™º "

[os.symbols]
Alpaquita         = "îª¢ "
Alpine            = "ïŒ€ "
Amazon            = "ï‰° "
Android           = "ï…» "
Arch              = "ïŒƒ "
Artix             = "ïŒŸ "
CentOS            = "ïŒ„ "
Debian            = "ïŒ† "
DragonFly         = "îŠ "
Emscripten        = "ïˆ… "
EndeavourOS       = "ï†— "
Fedora            = "ïŒŠ "
FreeBSD           = "ïŒŒ "
Garuda            = "ó°›“ "
Gentoo            = "ïŒ "
HardenedBSD       = "ó°Œ "
Illumos           = "ó°ˆ¸ "
Linux             = "ïŒš "
Mabox             = "î¬© "
Macos             = "ïŒ‚ "
Manjaro           = "ïŒ’ "
Mariner           = "ï‡ "
MidnightBSD       = "ï†† "
Mint              = "ïŒ "
NetBSD            = "ï€¤ "
NixOS             = "ïŒ“ "
OpenBSD           = "ó°ˆº "
openSUSE          = "ïŒ” "
OracleLinux       = "ó°Œ· "
Pop               = "ïŒª "
Raspbian          = "ïŒ• "
Redhat            = "ïŒ– "
RedHatEnterprise  = "ïŒ– "
Redox             = "ó°€˜ "
Solus             = "ó° ³ "
SUSE              = "ïŒ” "
Ubuntu            = "ïŒ› "
Unknown           = "ïˆ­ "
Windows           = "ó°² "

[package]
symbol            = "ó°— "

[perl]
symbol            = "î™¾ "

[php]
symbol            = "î˜ˆ "

[pijul_channel]
symbol            = "ï˜ "

[python]
symbol            = "îˆµ "

[rlang]
symbol            = "ó°Ÿ” "

[ruby]
symbol            = "î‘ "

[rust]
symbol            = "î¨ "

[scala]
symbol            = "îœ· "

[swift]
symbol            = "î• "

[zig]
symbol            = "îš© "

# Palettes ----------------------------------------------------------------------
[palettes.catppuccin_macchiato]
rosewater          = "#f4dbd6"
flamingo           = "#f0c6c6"
pink               = "#f5bde6"
mauve              = "#c6a0f6"
red                = "#ed8796"
maroon             = "#ee99a0"
peach              = "#f5a97f"
yellow             = "#eed49f"
green              = "#a6da95"
teal               = "#8bd5ca"
sky                = "#91d7e3"
sapphire           = "#7dc4e4"
blue               = "#8aadf4"
lavender           = "#b7bdf8"
text               = "#cad3f5"
subtext1           = "#b8c0e0"
subtext0           = "#a5adcb"
overlay2           = "#939ab7"
overlay1           = "#8087a2"
overlay0           = "#6e738d"
surface2           = "#5b6078"
surface1           = "#494d64"
surface0           = "#363a4f"
base               = "#24273a"
mantle             = "#1e2030"
crust              = "#181926"

[palettes.catppuccin_frappe]
rosewater          = "#f2d5cf"
flamingo           = "#eebebe"
pink               = "#f4b8e4"
mauve              = "#ca9ee6"
red                = "#e78284"
maroon             = "#ea999c"
peach              = "#ef9f76"
yellow             = "#e5c890"
green              = "#a6d189"
teal               = "#81c8be"
sky                = "#99d1db"
sapphire           = "#85c1dc"
blue               = "#8caaee"
lavender           = "#babbf1"
text               = "#c6d0f5"
subtext1           = "#b5bfe2"
subtext0           = "#a5adce"
overlay2           = "#949cbb"
overlay1           = "#838ba7"
overlay0           = "#737994"
surface2           = "#626880"
surface1           = "#51576d"
surface0           = "#414559"
base               = "#303446"
mantle             = "#292c3c"
crust              = "#232634"

[palettes.catppuccin_latte]
rosewater          = "#dc8a78"
flamingo           = "#dd7878"
pink               = "#ea76cb"
mauve              = "#8839ef"
red                = "#d20f39"
maroon             = "#e64553"
peach              = "#fe640b"
yellow             = "#df8e1d"
green              = "#40a02b"
teal               = "#179299"
sky                = "#04a5e5"
sapphire           = "#209fb5"
blue               = "#1e66f5"
lavender           = "#7287fd"
text               = "#4c4f69"
subtext1           = "#5c5f77"
subtext0           = "#6c6f85"
overlay2           = "#7c7f93"
overlay1           = "#8c8fa1"
overlay0           = "#9ca0b0"
surface2           = "#acb0be"
surface1           = "#bcc0cc"
surface0           = "#ccd0da"
base               = "#eff1f5"
mantle             = "#e6e9ef"
crust              = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater          = "#f5e0dc"
flamingo           = "#f2cdcd"
pink               = "#f5c2e7"
mauve              = "#cba6f7"
red                = "#f38ba8"
maroon             = "#eba0ac"
peach              = "#fab387"
yellow             = "#f9e2af"
green              = "#a6e3a1"
teal               = "#94e2d5"
sky                = "#89dceb"
sapphire           = "#74c7ec"
blue               = "#89b4fa"
lavender           = "#b4befe"
text               = "#cdd6f4"
subtext1           = "#bac2de"
subtext0           = "#a6adc8"
overlay2           = "#9399b2"
overlay1           = "#7f849c"
overlay0           = "#6c7086"
surface2           = "#585b70"
surface1           = "#45475a"
surface0           = "#313244"
base               = "#1e1e2e"
mantle             = "#181825"
crust              = "#11111b"

[palettes.solarized_light]
# background and content tones:
#                                # DARK MODE             | LIGHT MODE
base03             = '#002b36'   # background            | -
base02             = '#073642'   # background highlights | -
base01             = '#586e75'   # comments              | opt. emph. content
base00             = '#657b83'   # -                     | primary content
base0              = '#839496'   # primary content       | -
base1              = '#93a1a1'   # opt. emph. content    | comments
base2              = '#eee8d5'   # -                     | background highlights
base3              = '#fdf6e3'   # -                     | background
# accent colors:
sol_yellow         = '#b58900'
sol_orange         = '#cb4b16'
sol_red            = '#dc322f'
sol_magenta        = '#d33682'
sol_violet         = '#6c71c4'
sol_blue           = '#268bd2'
sol_cyan           = '#2aa198'
sol_green          = '#859900'

[palettes.zenwritten]
black              = '#EEEEEE'
blue               = '#286486'
cyan               = '#3B8992'
green              = '#4F6C31'
magenta            = '#88507D'
red                = '#A8334C'
white              = '#353535'
yellow             = '#944927'
bright_black       = '#C6C3C3'
bright_red         = '#94253E'
bright_green       = '#3F5A22'
bright_yellow      = '#803D1C'
bright_blue        = '#1D5573'
bright_magenta     = '#7B3B70'
bright_cyan        = '#2B747C'
bright_white       = '#5C5C5C'
